/**
 * Error identifiers for Sentry tracking and error categorization.
 * These IDs help correlate errors in production monitoring with specific code locations.
 */
export const ERROR_IDS = {
  // File I/O Errors
  PERMISSION_DENIED: "E_PERM_DENIED",
  NO_SUCH_FILE_OR_DIRECTORY: "E_NOENT",
  FILE_READ_FAILED: "E_FILE_READ",
  FILE_WRITE_FAILED: "E_FILE_WRITE",
  DIRECTORY_CREATE_FAILED: "E_MKDIR_FAILED",
  NO_SPACE_LEFT: "E_ENOSPC",
  READ_ONLY_FILESYSTEM: "E_EROFS",

  // Path Security Errors
  PATH_TRAVERSAL_ATTEMPT: "SEC_PATH_TRAVERSAL",
  INVALID_PATH: "SEC_INVALID_PATH",
  PATH_SPECIAL_CHARS: "SEC_PATH_SPECIAL_CHARS",

  // Command/Scanner Errors
  COMMAND_SCAN_FAILED: "SCAN_COMMAND_FAILED",
  COMMAND_DIRECTORY_NOT_FOUND: "SCAN_DIR_NOT_FOUND",
  COMMAND_DIRECTORY_PERMISSION_DENIED: "SCAN_DIR_PERMISSION",

  // MCP Errors
  MCP_LOAD_FAILED: "MCP_LOAD_FAILED",
  MCP_PARSE_ERROR: "MCP_PARSE_ERROR",
  MCP_FILE_NOT_FOUND: "MCP_FILE_NOT_FOUND",

  // Platform Adapter Errors
  ADAPTER_NOT_REGISTERED: "ADAPTER_NOT_REGISTERED",
  ADAPTER_RESOLUTION_FAILED: "ADAPTER_RESOLUTION",
  PLATFORM_CONFIG_WRITE_FAILED: "PLATFORM_CONFIG_WRITE",
  PLATFORM_CONFIG_READ_FAILED: "PLATFORM_CONFIG_READ",

  // CLI Errors
  CLI_INVALID_ARGUMENT: "CLI_INVALID_ARG",
  CLI_EXECUTION_FAILED: "CLI_EXECUTION",

  // System Errors
  SYSTEM_ERROR: "SYS_ERROR",
  PROGRAMMING_ERROR: "SYS_PROGRAMMING",
} as const;

export type ErrorId = (typeof ERROR_IDS)[keyof typeof ERROR_IDS];
